GET http://localhost:4000/ad

###

GET http://localhost:4000/ad?category=3

###

GET http://localhost:4000/ad/1

###

POST http://localhost:4000/ad
Content-Type: application/json

{
    "title": "Car to sell",
    "description":
      "My boat is green, working fine. I'm selling it because I've got a new one",
    "owner": "boat.seller@gmail.com",
    "price": 1000000,
    "imageUrl":"https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
    "location": "Paris",
    "createdAt": "2023-09-05T10:13:14.755Z",
    "category" : 2,
    "tags": [{"id":1},{"id":2}]
  }

###

DELETE http://localhost:3000/ad
Content-Type: application/json

{
  "id": 2
}

###
PUT http://localhost:4000/ad
Content-Type: application/json

{
  "idToEdit": 4,
  "newAd": {
    "category": 2
  } 
}