GET http://localhost:3000/ad

###

POST http://localhost:3000/ad
Content-Type: application/json

{
    "id": 3,
    "title": "Boat to sell",
    "description":
      "My boat is green, working fine. I'm selling it because I've got a new one",
    "owner": "boat.seller@gmail.com",
    "price": 1000000,
    "picture":"https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
    "location": "Paris",
    "createdAt": "2023-09-05T10:13:14.755Z",
    "category_id" : 1
  }

###

DELETE http://localhost:3000/ad
Content-Type: application/json

{
  "id": 1
}

###
PUT http://localhost:3000/ad
Content-Type: application/json

{
  "idToEdit": 3,
  "newAd": {
    "id" : 0,
    "title": "hoverboard",
    "description":
      "My hoverboard is green, working fine. I'm selling it because I've got a new one",
    "owner": "hoverboard.seller@gmail.com",
    "price": 555,
    "picture":"https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
    "location": "Paris",
    "createdAt": "2023-09-05T10:13:14.755Z"
  } 
}