GET http://localhost:4000/category

###

POST http://localhost:4000/category
Content-Type: application/json

{
    "name": "A supprimer"
}

###

PUT http://localhost:4000/category
Content-Type: application/json

{
    "id":3,
    "newCategory": {
        "name": "Informatique"
    }
}

###

DELETE http://localhost:4000/category
Content-Type: application/json

{
    "id":5
}